#!/bin/bash
php artisan infyom:scaffold activityLog --fromTable &&
php artisan infyom:scaffold Aplicacaos --fromTable &&
php artisan infyom:scaffold Bairros --fromTable &&
php artisan infyom:scaffold Causa_defeitos --fromTable &&
php artisan infyom:scaffold cidade --fromTable &&
php artisan infyom:scaffold Clientes --fromTable &&
php artisan infyom:scaffold Contrato_itens_ajuste --fromTable &&
php artisan infyom:scaffold Contrato_itens --fromTable &&
php artisan infyom:scaffold Contratos --fromTable &&
php artisan infyom:scaffold Controle_historicos --fromTable &&
php artisan infyom:scaffold Controle_motivos --fromTable &&
php artisan infyom:scaffold datosDoUsuario --fromTable &&
php artisan infyom:scaffold Defeitos_encontrados --fromTable &&
php artisan infyom:scaffold Digitacao_cadastros --fromTable &&
php artisan infyom:scaffold Empregados --fromTable &&
php artisan infyom:scaffold Empresas --fromTable &&
php artisan infyom:scaffold Estoque_entradas --fromTable &&
php artisan infyom:scaffold Estoque_entradas_produto --fromTable &&
php artisan infyom:scaffold Estoque_epi_epc_ferramental --fromTable &&
php artisan infyom:scaffold Estoque_epi_epc_ferramental_produtos --fromTable &&
php artisan infyom:scaffold Estoque_saida --fromTable &&
php artisan infyom:scaffold Estoque_saida_produtos --fromTable &&
php artisan infyom:scaffold Eventos_orcamento --fromTable &&
php artisan infyom:scaffold Eventos --fromTable &&
php artisan infyom:scaffold Fabricante --fromTable &&
php artisan infyom:scaffold fatura_evento --fromTable &&
php artisan infyom:scaffold Fatura_eventos_os --fromTable &&
php artisan infyom:scaffold Fatura_eventos --fromTable &&
php artisan infyom:scaffold fatura_manutencao_os --fromTable &&
php artisan infyom:scaffold Fatura_manutencao --fromTable &&
php artisan infyom:scaffold fatura_obras_os --fromTable &&
php artisan infyom:scaffold fatura_obras --fromTable &&
php artisan infyom:scaffold fornecedor --fromTable &&
php artisan infyom:scaffold funcip --fromTable &&
php artisan infyom:scaffold iluminacao_publica --fromTable &&
php artisan infyom:scaffold ipcontaip_10 --fromTable &&
php artisan infyom:scaffold ipcontaip_11 --fromTable &&
php artisan infyom:scaffold ipcontaip_12 --fromTable &&
php artisan infyom:scaffold ipcontaip_13 --fromTable &&
php artisan infyom:scaffold ipcontaip_14_dadosfatura --fromTable &&
php artisan infyom:scaffold ipcontaip_14 --fromTable &&
php artisan infyom:scaffold ipcontaip_estimada --fromTable &&
php artisan infyom:scaffold ipcontaip_medida --fromTable &&
php artisan infyom:scaffold ipcontaip_secretarias --fromTable &&
php artisan infyom:scaffold item --fromTable &&
php artisan infyom:scaffold lampada --fromTable &&
php artisan infyom:scaffold logradouro --fromTable &&
php artisan infyom:scaffold logradouro_tipo --fromTable &&
php artisan infyom:scaffold luminaria --fromTable &&
php artisan infyom:scaffold marca --fromTable &&
php artisan infyom:scaffold medidor --fromTable &&
php artisan infyom:scaffold mensagem --fromTable &&
php artisan infyom:scaffold meses --fromTable &&
php artisan infyom:scaffold objeto_iluminado --fromTable &&
php artisan infyom:scaffold obras_baixa_ip_anterior --fromTable &&
php artisan infyom:scaffold obras_baixa_ip --fromTable &&
php artisan infyom:scaffold obras_estoque --fromTable &&
php artisan infyom:scaffold obras_orcamento --fromTable &&
php artisan infyom:scaffold obras --fromTable &&
php artisan infyom:scaffold obras_solicitante --fromTable &&
php artisan infyom:scaffold operacao --fromTable &&
php artisan infyom:scaffold ordemDeServico --fromTable &&
php artisan infyom:scaffold origem_solicitacao --fromTable &&
php artisan infyom:scaffold pedido_cabecalho --fromTable &&
php artisan infyom:scaffold pedido --fromTable &&
php artisan infyom:scaffold pedido_produtos --fromTable &&
php artisan infyom:scaffold perfil_cadastro --fromTable &&
php artisan infyom:scaffold perfil --fromTable &&
php artisan infyom:scaffold poste --fromTable &&
php artisan infyom:scaffold produtos --fromTable &&
php artisan infyom:scaffold ra --fromTable &&
php artisan infyom:scaffold reator --fromTable &&
php artisan infyom:scaffold rede --fromTable &&
php artisan infyom:scaffold rele --fromTable &&
php artisan infyom:scaffold requisicao --fromTable &&
php artisan infyom:scaffold respostas_mensagem_diaria --fromTable &&
php artisan infyom:scaffold respostas --fromTable &&
php artisan infyom:scaffold respostas_usuarios --fromTable &&
php artisan infyom:scaffold sequencial --fromTable &&
php artisan infyom:scaffold solicitacao_material_itens --fromTable &&
php artisan infyom:scaffold solicitacao_material --fromTable &&
php artisan infyom:scaffold solicitacao_reclamacao --fromTable &&
php artisan infyom:scaffold solicitacao_reclamacao_solicitantes --fromTable &&
php artisan infyom:scaffold subestacao --fromTable &&
php artisan infyom:scaffold suporte --fromTable &&
php artisan infyom:scaffold tarifa --fromTable &&
php artisan infyom:scaffold tipoacao --fromTable &&
php artisan infyom:scaffold tipo_solicitacao --fromTable &&
php artisan infyom:scaffold tipo_solicitante --fromTable &&
php artisan infyom:scaffold transformador --fromTable &&
php artisan infyom:scaffold turma --fromTable &&
php artisan infyom:scaffold unidade --fromTable &&
php artisan infyom:scaffold usuario_cidade --fromTable &&
php artisan infyom:scaffold usuarioCidade --fromTable &&
php artisan infyom:scaffold usuario --fromTable &&
php artisan infyom:scaffold veiculos_movimentacao --fromTable &&
php artisan infyom:scaffold veiculos --fromTable &&
php artisan infyom:scaffold veiculos_servicos --fromTable
