<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\solicitacao_reclamacao;
use Faker\Generator as Faker;

$factory->define(solicitacao_reclamacao::class, function (Faker $faker) {

    return [
        'idcidade' => $faker->randomDigitNotNull,
        'protocolo_sistema' => $faker->word,
        'protocolo_falasalvador' => $faker->word,
        'protocolo_consorcio' => $faker->word,
        'data_atendimento' => $faker->date('Y-m-d H:i:s'),
        'hora_atendimento' => $faker->word,
        'horaregistro' => $faker->word,
        'temporegistro' => $faker->word,
        'solicitante_nome' => $faker->word,
        'solicitante_telefone' => $faker->word,
        'solicitante_email' => $faker->word,
        'poste_numero' => $faker->word,
        'luminaria_numero' => $faker->randomDigitNotNull,
        'idtiposolicitante' => $faker->randomDigitNotNull,
        'idtiposolicitacao' => $faker->randomDigitNotNull,
        'idlogradouro_cadastro' => $faker->randomDigitNotNull,
        'idbairro_cadastro' => $faker->randomDigitNotNull,
        'visavis_cadastro' => $faker->word,
        'referencia_cadastro' => $faker->word,
        'idlogradourotipo_informado' => $faker->randomDigitNotNull,
        'logradouro_descricao_informado' => $faker->word,
        'idbairro_informado' => $faker->randomDigitNotNull,
        'visavis_informado' => $faker->word,
        'referencia_informado' => $faker->text,
        'dadoscomplementares' => $faker->text,
        'servicosolicitado' => $faker->text,
        'incluidoem' => $faker->date('Y-m-d H:i:s'),
        'idusuario' => $faker->randomDigitNotNull,
        'idempresa' => $faker->randomDigitNotNull,
        'enviado_impressao' => $faker->randomDigitNotNull,
        'enviado_mobile' => $faker->randomDigitNotNull,
        'enviado_mobile_idturma' => $faker->randomDigitNotNull,
        'data_execucao' => $faker->word,
        'hora_execucao' => $faker->word,
        'data_baixa' => $faker->date('Y-m-d H:i:s'),
        'hora_baixa' => $faker->word,
        'acao_adotada' => $faker->word,
        'servico_realizado' => $faker->word,
        'poste_numero_executado' => $faker->word,
        'luminaria_numero_executado' => $faker->randomDigitNotNull,
        'iddefeitoencontrado' => $faker->randomDigitNotNull,
        'idcausadefeito' => $faker->randomDigitNotNull,
        'idturma' => $faker->randomDigitNotNull,
        'alterador_em' => $faker->date('Y-m-d H:i:s'),
        'idusuarioalterou' => $faker->randomDigitNotNull,
        'sfs_informar_ciencia' => $faker->randomDigitNotNull,
        'c_informar_ciencia' => $faker->randomDigitNotNull,
        'c_informar_concluida' => $faker->randomDigitNotNull,
        'sfs_informar_concluida' => $faker->randomDigitNotNull,
        'idfatura' => $faker->randomDigitNotNull,
        'tma_dias' => $faker->word,
        'tma_horas' => $faker->word,
        'referencia_poste_executado' => $faker->word,
        'tipo_acao' => $faker->word,
        'motivo_acao' => $faker->text,
        'garantia' => $faker->randomDigitNotNull,
        'garantia_os_anterior' => $faker->word,
        'supervisor' => $faker->word,
        'motivo_atraso' => $faker->word,
        'app_coordenada_x' => $faker->word,
        'app_coordenada_y' => $faker->word,
        'app_informacoes_gerais' => $faker->text,
        'controle_idturma' => $faker->randomDigitNotNull,
        'controle_data_entrega' => $faker->date('Y-m-d H:i:s'),
        'controle_data_recebido' => $faker->date('Y-m-d H:i:s'),
        'controle_acao' => $faker->word,
        'controle_idmotivo' => $faker->randomDigitNotNull,
        'impressoem' => $faker->date('Y-m-d H:i:s'),
        'impressopor' => $faker->randomDigitNotNull,
        'os_separada_em' => $faker->date('Y-m-d H:i:s'),
        'os_separada_por' => $faker->randomDigitNotNull,
        'os_separada_para' => $faker->randomDigitNotNull,
        'created_at' => $faker->date('Y-m-d H:i:s'),
        'updated_at' => $faker->date('Y-m-d H:i:s'),
        'deleted_at' => $faker->date('Y-m-d H:i:s')
    ];
});
